// This file is generated by ts-rs from Rust types during build.
// It is checked in to avoid TS import errors during development.
// The build will overwrite it when compiling the Rust crate.

export interface ClipboardItem {
  id: string;
  content: string;
  content_type: string;
  timestamp: number;
  image_base64: string | null;
  image_width: number | null;
  image_height: number | null;
}
