name: recall
base: core22
version: '0.1.0'
summary: Gestionnaire de presse-papiers
description: |
  Recall est une application légère et rapide qui vous permet de stocker,
  organiser et retrouver facilement les éléments de votre presse-papiers.
  Développée avec Tauri, elle offre des performances natives tout en
  utilisant une interface web moderne.

grade: stable
confinement: strict
license: MIT

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  recall:
    command: usr/bin/recall
    desktop: usr/share/applications/recall.desktop
    extensions: [ gnome ]
    plugs:
      - removable-media

parts:
  build-app:
    plugin: dump
    source: .
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - pkg-config
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libxcb-shape0
      - libatk-adaptor
    override-build: |
      set -eux
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      export PATH="$HOME/.cargo/bin:$PATH"
      npm install
      npm run tauri build -- --bundles deb
      dpkg -x target/release/bundle/deb/*.deb "$SNAPCRAFT_PART_INSTALL/"
